name: Push Trigger Every 10 Minutes
# push
on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Timestamp
        run: |
          echo "Triggered at $(date -u)" > trigger.txt

      - name: Commit & Push
        run: |
          git config user.name "auto-bot"
          git config user.email "actions@github.com"
          git add trigger.txt
          git commit -m "⚡ Trigger: $(date -u)" || echo "No changes to commit"
          git push
