name: Push Trigger Every 10 Minutes
# push
on:
  schedule:
    - cron: '*/5 * * * *'  # runs every 10 minutes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Timestamp
        run: |
          echo "Triggered at $(date -u)" > trigger.txt

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add trigger.txt
          git commit -m "⚡ Trigger: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          git push
