name: Push Trigger Every 10 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # every 10 minutes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Timestamp
        run: |
          echo "Triggered at $(date -u)" > .github/workflows/trigger.txt

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
          git add .github/workflows/trigger.txt
          git commit -m "⚡ Trigger: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
