name: Schedule Test
on:
  schedule:
    - cron: "*/1 * * * *"  # every 5 mins for testing
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Echo time
        run: echo "⏰ Scheduled run at $(date -u)"
